name: Selenium Python Tests on Windows

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium pytest html-testRunner

      - name: Add chromedriver to PATH
        run: |
          copy web\resources\driver\chromedriver.exe C:\Windows\System32

      - name: Run tests
        run: pytest ./web/tests
